name: things
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_messaging: ^15.2.4
  firebase_core: ^3.12.1

  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.4

  cached_network_image: ^3.4.1

  get_storage: ^2.1.1
  device_info_plus: ^11.3.3
  easy_localization: ^3.0.7+1

  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/strings/
    - assets/images/
