// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfy1xv5phCN4xFiOufRjKdFB4CwV5CXKU',
    appId: '1:857622757347:web:b1d95d57bd0ae0f47caad6',
    messagingSenderId: '857622757347',
    projectId: 'things-comma',
    authDomain: 'things-comma.firebaseapp.com',
    storageBucket: 'things-comma.firebasestorage.app',
    measurementId: 'G-N89XVFPM0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKWZd5zfjisJf4pPUSweY4eX4-OofT5M',
    appId: '1:857622757347:android:353d4cbae645752a7caad6',
    messagingSenderId: '857622757347',
    projectId: 'things-comma',
    storageBucket: 'things-comma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7NMLbIcRdd0HgGUpTyYQeXg1j-tdheK4',
    appId: '1:857622757347:ios:42452f53bb62b08a7caad6',
    messagingSenderId: '857622757347',
    projectId: 'things-comma',
    storageBucket: 'things-comma.firebasestorage.app',
    iosBundleId: 'com.comma.things',
  );
}
