// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqFNwH8Fx70AJgE6_m6iA46jff6UKjaKQ',
    appId: '1:289243395985:web:08f57e0343e10f16fe0c30',
    messagingSenderId: '289243395985',
    projectId: 'ashyaa-comma',
    authDomain: 'ashyaa-comma.firebaseapp.com',
    storageBucket: 'ashyaa-comma.firebasestorage.app',
    measurementId: 'G-2PD2167ZHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcLVSyPCfGd3yxPG2bulIP0nEx4tsgQ5c',
    appId: '1:289243395985:android:852d9876d4947b72fe0c30',
    messagingSenderId: '289243395985',
    projectId: 'ashyaa-comma',
    storageBucket: 'ashyaa-comma.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaoVo6_ku_ip8GlT5Zets7JdqH2-8lZSc',
    appId: '1:289243395985:ios:6473837ec115e82afe0c30',
    messagingSenderId: '289243395985',
    projectId: 'ashyaa-comma',
    storageBucket: 'ashyaa-comma.firebasestorage.app',
    iosBundleId: 'com.comma.ashyaa',
  );
}
